# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171018_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='hide_user',
        ),
    ]
